### ISSUE TITLE
最新版本键位不当

### ISSUE THREAD

**Issue by ghost** [cubercsl/rime-flypy#7]
如「强」（ql）错误的成了其他码。使用者应当退回到上一个版本

**Comment by cubercsl** [comment]
https://github.com/cubercsl/rime-flypy/blob/0279736af6df4e73f2076241483a576ec1ed9971/flypy.dict.yaml#L37657

请提供详细的软件版本，和复现步骤。我这里没有问题

**Comment by ghost** [comment]
> https://github.com/cubercsl/rime-flypy/blob/0279736af6df4e73f2076241483a576ec1ed9971/flypy.dict.yaml#L37657
> 
> 请提供详细的软件版本，和复现步骤。我这里没有问题

系 v20240521版本。
我使用aur安装flypy包，部署后即出问题。目前回退到了v10.9.5版本。
